// Services barrel export
export * from './storage';
export * from './gasSync';
export * from './searchSuggestion';
export * from './cache';
export * from './memory';
export * from './memoryManager';
export * from './swCache';
export * from './http3';
export * from './sessionRestore';
export * from './tabCompressor';
export * from './startupOptimizer';
export * from './processIsolation';
export * from './cpuScheduler';
export * from './tabLayout';
export * from './predictiveLoader';
export * from './performanceDashboard.jsx';
